export const AlarmsList = [
  { number: "A000", name: "IMMINENT STOP" },
  { number: "A001", name: "OVERLOAD ALARM" },
  { number: "A002", name: "AMBIENT TEMPERATURE ALARM" },
  { number: "A003", name: "TRANSFER LOCKED" },
  { number: "A004", name: "TRANSFER IMPOSSIBLE" },
  { number: "A005", name: "INSUFFICIENT RESOURCES" },
  { number: "A006", name: "REDUNDANCY LOST" },
  { number: "A007", name: "OUTPUT SHORT CIRCUIT DETECTION" },
  { number: "A008", name: "ECO MODE DISABLED BY UPS" },
  { number: "A009", name: "ENERGY SAVER DISABLED BY UPS" },
  { number: "A010", name: "ON BYPASS FOR 1 HOUR" },
  { number: "A011", name: "WRONG PROFILE PASSWORD ENTERED" },
  { number: "A012", name: "MAINTENANCE ALARM" },
  { number: "A013", name: "REMOTE SERVICE ALARM" },
  { number: "A014", name: "REMOTE SERVICE PREVENTIVE ALARM" },
  { number: "A015", name: "GENERAL ALARM" },
  { number: "A016", name: "BATTERY DISCONNECTED" },
  { number: "A017", name: "BATTERY DISCHARGED" },
  { number: "A018", name: "END OF BACK-UP TIME" },
  { number: "A019", name: "OPERATING ON BATTERY" },
  { number: "A020", name: "BATTERY TEMPERATURE ALARM" },
  { number: "A021", name: "BATTERY ROOM ALARM" },
  { number: "A022", name: "BATTERY TEST FAILED" },
  { number: "A023", name: "BMS HAS DETECTED A WEAK STRING" },
  { number: "A024", name: "AT LEAST ONE BATTERY STRING OPEN" },
  { number: "A025", name: "ON BATTERY WITH MAINS OK" },
  { number: "A026", name: "INSULATION FAULT" },
  { number: "A027", name: "BATTERY ALARM" },
  { number: "A028", name: "BATTERY PREVENTIVE ALARM" },
  { number: "A029", name: "UPS BACKUP CRITICAL ALARM" },
  { number: "A030", name: "UPS BACKUP PREVENTIVE ALARM" },
  { number: "A031", name: "UPS BACKUP NOT OK" },
  { number: "A032", name: "RECTIFIER CRITICAL ALARM" },
  { number: "A033", name: "RECTIFIER PREVENTIVE ALARM" },
  { number: "A034", name: "RECTIFIER REDUNDANCY ALARM" },
  { number: "A035", name: "RECTIFIER INPUT SUPPLY NOT OK" },
  { number: "A036", name: "GEN SET ALARM" },
  { number: "A037", name: "CHARGER CRITICAL ALARM" },
  { number: "A038", name: "CHARGER PREVENTIVE ALARM" },
  { number: "A039", name: "BATTERY CHARGE INTERRUPTED" },
  { number: "A040", name: "INVERTER CRITICAL ALARM" },
  { number: "A041", name: "INVERTER PREVENTIVE ALARM" },
  { number: "A042", name: "INVERTER REDUNDANCY ALARM" },
  { number: "A043", name: "IMMINENT REDUNDANCY LOST" },
  { number: "A044", name: "CONSUMABLE ALARM" },
  { number: "A045", name: "UNIT REDUNDANCY LOST" },
  { number: "A046", name: "PARALLEL BOARD CRITICAL ALARM" },
  { number: "A047", name: "PARALLEL BOARD PREVENTIVE ALARM" },
  { number: "A048", name: "BYPASS CRITICAL ALARM" },
  { number: "A049", name: "BYPASS PREVENTIVE ALARM" },
  { number: "A050", name: "BYPASS INPUT SUPPLY NOT OK" },
  { number: "A051", name: "PHASE ROTATION FAULT" },
  { number: "A052", name: "BYPASS BACK-FEED DETECTION" },
  { number: "A053", name: "TRANSFORMER ALARM" },
  { number: "A054", name: "FAN FAILURE" },
  { number: "A055", name: "ACS ALARM" },
  { number: "A056", name: "MAINTENANCE BYPASS ALARM" },
  { number: "A057", name: "INTERNAL BACK-FEED DETECTION" },
  { number: "A058", name: "BATTERY MONITORING ALARM" },
  { number: "A059", name: "UPS POWER OFF" },
  { number: "A060", name: "WRONG CONFIGURATION" },
  { number: "A061", name: "INTERNAL/COMMUNICATION FAILURE" },
  { number: "A062", name: "OPTION BOARD ALARM" },
  { number: "A063", name: "SPARE PARTS NOT COMPATIBLE" },
  { number: "A064", name: "PROGRAMMABLE A064" },
  { number: "A065", name: "PROGRAMMABLE A065" },
  { number: "A066", name: "PROGRAMMABLE A066" },
  { number: "A067", name: "PROGRAMMABLE A067" },
  { number: "A068", name: "PROGRAMMABLE A068" },
  { number: "A069", name: "PROGRAMMABLE A069" },
  { number: "A070", name: "PROGRAMMABLE A070" },
  { number: "A071", name: "PROGRAMMABLE A071" },
  { number: "A072", name: "LINE-INTERACTIVE MODE DISABLED BY UPS" },
  { number: "A073", name: "FREE" },
  { number: "A074", name: "FREE" },
  { number: "A075", name: "FREE" },
  { number: "A076", name: "FREE" },
  { number: "A077", name: "FREE" },
  { number: "A078", name: "FREE" },
  { number: "A079", name: "FREE" },
  { number: "A080", name: "CUSTOMER INSTALLATION OVERLOAD" },
  { number: "A081", name: "FREE" },
  { number: "A082", name: "FREE" },
  { number: "A083", name: "FREE" },
  { number: "A084", name: "FREE" },
  { number: "A085", name: "FREE" },
  { number: "A086", name: "FREE" },
  { number: "A087", name: "FREE" },
  { number: "A088", name: "FREE" },
  { number: "A089", name: "FREE" },
  { number: "A090", name: "FREE" },
  { number: "A091", name: "FREE" },
  { number: "A092", name: "OVERLOAD PRE ALARM" },
  { number: "A093", name: "BATTERY VOLTAGE OUT OF RANGE" },
  { number: "A094", name: "BATTERY CHARGER FAILURE" },
  { number: "A095", name: "BATTERY DEEP DISCHARGE PROTECTION INITIATED" },
  { number: "A096", name: "[1] IN GENERAL ALARM" },
  { number: "A097", name: "[2] IN GENERAL ALARM" },
  { number: "A098", name: "[3] IN GENERAL ALARM" },
  { number: "A099", name: "[4] IN GENERAL ALARM" },
  { number: "A100", name: "[5] IN GENERAL ALARM" },
  { number: "A101", name: "[6] IN GENERAL ALARM" },
  { number: "A102", name: "[7] IN GENERAL ALARM" },
  { number: "A103", name: "[8] IN GENERAL ALARM" },
  { number: "A104", name: "[9] IN GENERAL ALARM" },
  { number: "A105", name: "[10] IN GENERAL ALARM" },
  { number: "A106", name: "[11] IN GENERAL ALARM" },
  { number: "A107", name: "[12] IN GENERAL ALARM" },
  { number: "A108", name: "[13] IN GENERAL ALARM" },
  { number: "A109", name: "[14] IN GENERAL ALARM" },
  { number: "A110", name: "[15] IN GENERAL ALARM" },
  { number: "A111", name: "FREE" },
  { number: "A112", name: "[1] IN IMMINENT STOP" },
  { number: "A113", name: "[2] IN IMMINENT STOP" },
  { number: "A114", name: "[3] IN IMMINENT STOP" },
  { number: "A115", name: "[4] IN IMMINENT STOP" },
  { number: "A116", name: "[5] IN IMMINENT STOP" },
  { number: "A117", name: "[6] IN IMMINENT STOP" },
  { number: "A118", name: "[7] IN IMMINENT STOP" },
  { number: "A119", name: "[8] IN IMMINENT STOP" },
  { number: "A120", name: "[9] IN IMMINENT STOP" },
  { number: "A121", name: "[10] IN IMMINENT STOP" },
  { number: "A122", name: "[11] IN IMMINENT STOP" },
  { number: "A123", name: "[12] IN IMMINENT STOP" },
  { number: "A124", name: "[13] IN IMMINENT STOP" },
  { number: "A125", name: "[14] IN IMMINENT STOP" },
  { number: "A126", name: "[15] IN IMMINENT STOP" },
  { number: "A127", name: "FREE" },
];
