import Measure from "./Measure";

export const MeasuresList = [
  new Measure("M000", "Output load rate", "%", 1, 1, false),
  new Measure("M001", "Output load rate L1", "%", 1, 1, false),
  new Measure("M002", "Output load rate L2", "%", 1, 1, false),
  new Measure("M003", "Output load rate L3", "%", 1, 1, false),
  new Measure("M004", "Output", "kVA", 1, 10, false),
  new Measure("M005", "Output", "kW", 1, 10, false),
  new Measure("M006", "Output current L1", "A", 1, 10, false),
  new Measure("M007", "Output current L2", "A", 1, 10, false),
  new Measure("M008", "Output current L3", "A", 1, 10, false),
  new Measure("M009", "Ouput neutral current", "A", 1, 10, false),
  new Measure("M010", "Output voltage L1", "V", 1, 1, false),
  new Measure("M011", "Output voltage L2", "V", 1, 1, false),
  new Measure("M012", "Output voltage L3", "V", 1, 1, false),
  new Measure("M013", "Output frequency", "Hz", 10, 10, false),
  new Measure("M014", "Output Crest Factor", "", 10, 10, false),
  new Measure("M015", "Ambient T°", "°C", 10, 10, true),
  new Measure("M016", "Battery voltage string +", "V", 1, 10, true),
  new Measure("M017", "Battery voltage string -", "V", 1, 10, true),
  new Measure("M018", "Battery voltage string +", "A", 1, 10, true),
  new Measure("M019", "Battery voltage string -", "A", 1, 10, true),
  new Measure("M020", "", "", 1, 1, false),
  new Measure("M021", "Battery minSOH (Step Of Health)", "", 1, 1, false),
  new Measure("M022", "Battery capacity", "%", 1, 1, false),
  new Measure("M023", "Battery capacity", "Ah", 1, 10, false),
  new Measure("M024", "Bat. Remaining backup time", "mn", 1, 1, false),
  new Measure("M025", "Time on battery", "s", 60, 60, false),
  new Measure("M026", "Battery temperature", "°C", 10, 10, true),
  new Measure("M027", "Battery temperature average", "°C", 10, 10, true),
  new Measure("M028", "UPS Backup VDC", "V", 1, 10, false),
  new Measure("M029", "UPS Backup temperature", "°C", 10, 10, true),
  new Measure("M030", "UPS Backup Backup time", "s", 1, 1, false),
  new Measure("M031", "", "", 1, 1, false),
  new Measure("M032", "Rect. input supply volt. L1", "V", 1, 1, false),
  new Measure("M033", "Rect. input supply volt. L2", "V", 1, 1, false),
  new Measure("M034", "Rect. input supply volt. L3", "V", 1, 1, false),
  new Measure("M035", "Rect. input supply freq.	", "Hz", 10, 10, false),
  new Measure("M036", "Rect. input supply volt. U12", "V", 1, 1, false),
  new Measure("M037", "Rect. input supply volt. U23", "V", 1, 1, false),
  new Measure("M038", "Rect. input supply volt. U31", "V", 1, 1, false),
  new Measure("M039", "Bypass input supply voltage L1", "V", 1, 1, false),
  new Measure("M040", "Bypass input supply voltage L2", "V", 1, 1, false),
  new Measure("M041", "Bypass input supply voltage L3", "V", 1, 1, false),
  new Measure("M042", "Bypass input supply freq.", "Hz", 10, 10, false),
  new Measure("M043", "Bypass input supply voltage U12", "V", 1, 1, false),
  new Measure("M044", "Bypass input supply voltage U23", "V", 1, 1, false),
  new Measure("M045", "Bypass input supply voltage U31", "V", 1, 1, false),
  new Measure("M046", "Neutral load rate", "", 1, 1, false),
  new Measure("M047", "Reserved", "", 1, 1, false),
  new Measure("M048", "Output Apparent P. L1", "kVA", 1, 10, false),
  new Measure("M049", "Output Apparent P. L2", "kVA", 1, 10, false),
  new Measure("M050", "Output Apparent P. L3", "kVA", 1, 10, false),
  new Measure("M051", "Output Active Power L1", "kW", 1, 10, false),
  new Measure("M052", "Output Active Power L2", "kW", 1, 10, false),
  new Measure("M053", "Output Active Power L3", "kW", 1, 10, false),
  new Measure("M054", "Output voltage U12", "V", 1, 1, false),
  new Measure("M055", "Output voltage U23", "V", 1, 1, false),
  new Measure("M056", "Output voltage U31", "V", 1, 1, false),
  new Measure("M057", "Output Power factor L1", "", 100, 100, true),
  new Measure("M058", "Output Power factor L2", "", 100, 100, true),
  new Measure("M059", "Output Power factor L3", "", 100, 100, true),
  new Measure("M060", "Output Crest Factor L1", "", 10, 10, false),
  new Measure("M061", "Output Crest Factor L2", "", 10, 10, false),
  new Measure("M062", "Output Crest Factor L3", "", 10, 10, false),
  new Measure("M063", "Output Crest Factor neutral", "", 10, 10, false),
  new Measure("M064", "Rect. Input Current L1", "A", 1, 10, false),
  new Measure("M065", "Rect. Input Current L2", "A", 1, 10, false),
  new Measure("M066", "Rect. Input Current L3", "A", 1, 10, false),
  new Measure("M067", "Rect. Active Power L1", "kW", 1, 10, true),
  new Measure("M068", "Rect. Active Power L2", "kW", 1, 10, true),
  new Measure("M069", "Rect. Active Power L3", "kW", 1, 10, true),
  new Measure("M070", "Bypass Input Current L1", "A", 1, 10, false),
  new Measure("M071", "Bypass Input Current L2", "A", 1, 10, false),
  new Measure("M072", "Bypass Input Current L3", "A", 1, 10, false),
  new Measure("M073", "Bypass Power L1", "kW", 1, 10, false),
  new Measure("M074", "Bypass Power L2", "kW", 1, 10, false),
  new Measure("M075", "Bypass Power L3", "kW", 1, 10, false),
  new Measure("M076", "phase shift", "", 1, 1, true),
  new Measure("M077", "Step number of procedure to display", "", 1, 1, false),
  new Measure("M078", "Status LED color code", "", 1, 1, false),
  new Measure("M079", "ACT alarm number", "", 1, 1, false),
];
