export const StatesList = [
  { number: "S000", name: "LOAD PROTECTED BY INVERTER" },
  { number: "S001", name: "LOAD SUPPLIED IN NORMAL MODE" },
  { number: "S002", name: "LOAD SUPPLIED BY AUTOMATIC BYPASS" },
  { number: "S003", name: "LOAD SUPPLIED BY MAINTENANCE BYPASS" },
  { number: "S004", name: "LOAD OFF" },
  { number: "S005", name: "FREE" },
  { number: "S006", name: "UPS IN ECO MODE" },
  { number: "S007", name: "UPS IN ENERGY SAVER" },
  { number: "S008", name: "HEAT RUN MODE" },
  { number: "S009", name: "IN SERVICE MODE" },
  { number: "S010", name: "LINE-INTERACTIVE MODE" },
  { number: "S011", name: "OPERATING" },
  { number: "S012", name: "AVAILABLE" },
  { number: "S013", name: "ON STANDBY" },
  { number: "S014", name: "UNIT ISOLATED" },
  { number: "S015", name: "MAINTENANCE ALERT" },
  { number: "S016", name: "OUTPUT BREAKER CLOSED " },
  { number: "S017", name: "MAINTENANCE BYPASS CLOSED " },
  { number: "S018", name: "EXTERNAL MAINTENANCE BYPASS CLOSED" },
  { number: "S019", name: "EXTERNAL OUTPUT BREAKER CLOSED" },
  { number: "S020", name: "SINGLE PHASE INPUT SUPPLY" },
  { number: "S021", name: "RECTIFIER INPUT BREAKER CLOSED" },
  { number: "S022", name: "BYPASS INPUT BREAKER CLOSED" },
  { number: "S023", name: "GEN SET ON" },
  { number: "S024", name: "BUS BAR 1 CLOSED " },
  { number: "S025", name: "BUS BAR 2 CLOSED " },
  { number: "S026", name: "AUTOMATIC START IN PROGRESS" },
  { number: "S027", name: "MAINTENANCE BYPASS PROCEDURE IN PROGRESS" },
  { number: "S028", name: "UPS OFF PROCEDURE IN PROGRESS" },
  { number: "S029", name: "BYPASS EXTRACTION PROCEDURE" },
  { number: "S030", name: "AUTO-TEST PROCEDURE IN PROGRESS" },
  { number: "S031", name: "ALARM ACKNOWLEDGEMENT REQUESTED" },
  { number: "S032", name: "BATTERY OK" },
  { number: "S033", name: "BATTERY CHARGED" },
  { number: "S034", name: "BATTERY TEST IN PROGRESS" },
  { number: "S035", name: "BATTERY TEST PROGRAMMED" },
  { number: "S036", name: "BATTERY CHARGING" },
  { number: "S037", name: "BATTERY TEST INTERRUPTED" },
  { number: "S038", name: "FLOATING VOLTAGE REDUCED" },
  { number: "S039", name: "BATTERY DISCHARGE TO INPUT" },
  { number: "S040", name: "UPS BACKUP SYSTEM CONNECTED" },
  { number: "S041", name: "UPS BACKUP SYSTEM CHARGED/READY" },
  { number: "S042", name: "UPS BACKUP SYSTEM CHARGING" },
  { number: "S043", name: "FREE" },
  { number: "S044", name: "ALL INVERTERS ARE ON" },
  { number: "S045", name: "ALL RECTIFIERS ARE ON" },
  { number: "S046", name: "ALL BYPASSES ARE AVAILABLE" },
  { number: "S047", name: "ALL UNITS OR MODULES ARE AVAILABLE" },
  { number: "S048", name: "RECTIFIER INPUT SUPPLY PRESENT" },
  { number: "S049", name: "RECTIFIER ON" },
  { number: "S050", name: "CHARGER ON" },
  { number: "S051", name: "RECTIFIER IS STARTING" },
  { number: "S052", name: "INVERTER ON" },
  { number: "S053", name: "INVERTER SWITCH ON" },
  { number: "S054", name: "FREE" },
  { number: "S055", name: "BYPASS OUTPUT BREAKER CLOSED" },
  { number: "S056", name: "BYPASS INPUT SUPPLY PRESENT" },
  { number: "S057", name: "BYPASS STATIC SWITCH CLOSED" },
  { number: "S058", name: "BYPASS INPUT & INVERTER SYNCHRONISED" },
  { number: "S059", name: "ACS EXTERNAL SYNCHRONISATION" },
  { number: "S060", name: "POWERSHARE PLUG 1 CLOSED" },
  { number: "S061", name: "POWERSHARE PLUG 2 CLOSED" },
  { number: "S062", name: "POWERSHARE PLUG 3 CLOSED" },
  { number: "S063", name: "POWERSHARE PLUG 4 CLOSED" },
  { number: "S064", name: "CARD IN SLOT 1 PRESENT" },
  { number: "S065", name: "CARD IN SLOT 2 PRESENT" },
  { number: "S066", name: "CARD IN SLOT 1-EXT PRESENT" },
  { number: "S067", name: "CARD IN SLOT 2-EXT PRESENT" },
  { number: "S068", name: "CARD IN SLOT 3/SYST PRESENT" },
  { number: "S069", name: "CARD IN SLOT 3-EXT PRESENT" },
  { number: "S070", name: "PROFILE 1 LOGIN" },
  { number: "S071", name: "PROFILE 2 LOGIN" },
  { number: "S072", name: "PROGRAMMABLE S072" },
  { number: "S073", name: "PROGRAMMABLE S073" },
  { number: "S074", name: "PROGRAMMABLE S074" },
  { number: "S075", name: "PROGRAMMABLE S075" },
  { number: "S076", name: "PROGRAMMABLE S076" },
  { number: "S077", name: "PROGRAMMABLE S077" },
  { number: "S078", name: "PROGRAMMABLE S078" },
  { number: "S079", name: "PROGRAMMABLE S079" },
  { number: "S080", name: "MODULE INSERTION PROCEDURE" },
  { number: "S081", name: "MODULE EXTRACTION PROCEDURE" },
  { number: "S082", name: "FREE" },
  { number: "S083", name: "FREE" },
  { number: "S084", name: "BACKFEED PROTECTION OPENED" },
  { number: "S085", name: "FREE" },
  { number: "S086", name: "FREE" },
  { number: "S087", name: "FREE" },
  { number: "S088", name: "FREE" },
  { number: "S089", name: "FREE" },
  { number: "S090", name: "FREE" },
  { number: "S091", name: "FREE" },
  { number: "S092", name: "FREE" },
  { number: "S093", name: "FREE" },
  { number: "S094", name: "FREE" },
  { number: "S095", name: "FREE" },
  { number: "S096", name: "[1] IS OPERATING" },
  { number: "S097", name: "[2] IS OPERATING" },
  { number: "S098", name: "[3] IS OPERATING" },
  { number: "S099", name: "[4] IS OPERATING" },
  { number: "S100", name: "[5] IS OPERATING" },
  { number: "S101", name: "[6] IS OPERATING" },
  { number: "S102", name: "[7] IS OPERATING" },
  { number: "S103", name: "[8] IS OPERATING" },
  { number: "S104", name: "[9] IS OPERATING" },
  { number: "S105", name: "[10] IS OPERATING" },
  { number: "S106", name: "[11] IS OPERATING" },
  { number: "S107", name: "[12] IS OPERATING" },
  { number: "S108", name: "[13] IS OPERATING" },
  { number: "S109", name: "[14] IS OPERATING" },
  { number: "S110", name: "[15] IS OPERATING" },
  { number: "S111", name: "FREE" },
  { number: "S112", name: "[1] IS AVAILABLE" },
  { number: "S113", name: "[2] IS AVAILABLE" },
  { number: "S114", name: "[3] IS AVAILABLE" },
  { number: "S115", name: "[4] IS AVAILABLE" },
  { number: "S116", name: "[5] IS AVAILABLE" },
  { number: "S117", name: "[6] IS AVAILABLE" },
  { number: "S118", name: "[7] IS AVAILABLE" },
  { number: "S119", name: "[8] IS AVAILABLE" },
  { number: "S120", name: "[9] IS AVAILABLE" },
  { number: "S121", name: "[10] IS AVAILABLE" },
  { number: "S122", name: "[11] IS AVAILABLE" },
  { number: "S123", name: "[12] IS AVAILABLE" },
  { number: "S124", name: "[13] IS AVAILABLE" },
  { number: "S125", name: "[14] IS AVAILABLE" },
  { number: "S126", name: "[15] IS AVAILABLE" },
  { number: "S127", name: "DATA NO LONGER UPDATED" },
];
